# jnext copper test cases (z88dk / zcc)
#
#   make list                     show the cases
#   make CASE=<name>              build build/<name>.nex
#   make CASE=<name> jnext        build and run it in jnext
#   make CASE=<name> shot         build and save a headless jnext screenshot
#   make CASE=<name> mame         build, copy to the SD image and run in MAME
#   make clean                    remove build artefacts
#
# CASE defaults to the case the repository is currently reporting.

CASE ?= layer2-bank-midline
CASEDIR := cases/$(CASE)

CC     := zcc
TARGET := +zxn -subtype=nex
CLIB   := sdcc_iy
CRT    := 31

TXT2BAS    := txt2bas          # npm install -g txt2bas
MAME       := mame
NEXT_IMAGE := $(HOME)/bin/next-images/cspect-next-2gb.img
SD_IMAGE_PART_OFFSET := 32256
export MTOOLS_SKIP_CHECK := 1

MAME_FLAGS := -snapsize 1440x1080 -ui_active -console -nounevenstretch \
              -video bgfx -bgfx_screen_chains unfiltered -window -skip_gameinfo \
              tbblue -hard1 $(NEXT_IMAGE)

CFLAGS  := $(TARGET) -vn -c -compiler=sdcc -clib=$(CLIB) \
           -SO3 --max-allocs-per-node200000 $(EXTRA_FLAGS)
ASFLAGS := $(TARGET) -vn -c -clib=$(CLIB) $(EXTRA_FLAGS)
LDFLAGS := $(TARGET) -vn -clib=$(CLIB) -startup=$(CRT) -m --list

OUTDIR := build
OUT    := $(OUTDIR)/$(CASE).nex

SRCS_C   := $(wildcard $(CASEDIR)/*.c)
SRCS_ASM := $(wildcard $(CASEDIR)/*.asm)
OBJS     := $(SRCS_C:.c=.o) $(SRCS_ASM:.asm=.o)

# The frame the screenshot is taken at, and the clock it is taken with. Both
# are pinned so two runs of the same build produce byte-identical PNGs.
SHOT_FRAME ?= 120
SHOT_RTC   ?= 2026-01-01 00:00:00

ifeq ($(SRCS_C)$(SRCS_ASM),)
$(error no sources in $(CASEDIR) -- run "make list" to see the cases)
endif

all: $(OUT)

list:
	@echo "cases:"
	@for d in cases/*/; do echo "  $$(basename $$d)"; done
	@echo "current CASE = $(CASE)"

# rebuild whenever the flags in this file change
$(OBJS): Makefile

$(OUT): $(OBJS) | $(OUTDIR)
	$(CC) $(LDFLAGS) -o $(OUTDIR)/$(CASE).bin $(OBJS) -create-app

$(OUTDIR):
	mkdir -p $(OUTDIR)

%.o: %.c
	$(CC) $(CFLAGS) $< -o $@

%.o: %.asm
	$(CC) $(ASFLAGS) $< -o $@

jnext: $(OUT)
	jnext --load $(OUT)

# A deterministic headless capture, which is how the PNGs in each case
# directory were produced.
shot: $(OUT)
	jnext --headless --silent --log-file $(OUTDIR)/jnext.log \
		--rtc "$(SHOT_RTC)" \
		--delayed-screenshot $(OUTDIR)/$(CASE)-jnext.png \
		--delayed-screenshot-frames $(SHOT_FRAME) \
		--delayed-automatic-exit-frames $$(($(SHOT_FRAME) + 10)) \
		$(OUT)
	@echo "wrote $(OUTDIR)/$(CASE)-jnext.png"

autoexec:
	@printf '%s\n' \
		'10 REM $(CASE)' \
		'15 REM Autoexec generated by Makefile' \
		'20 CD "c:/home/$(CASE)"' \
		'40 .nexload $(CASE).nex' \
		| $(TXT2BAS) -A 10 \
		| mcopy -i "$(NEXT_IMAGE)@@$(SD_IMAGE_PART_OFFSET)" -D o - ::/nextzxos/autoexec.bas

sync: $(OUT) autoexec
	mmd -i "$(NEXT_IMAGE)@@$(SD_IMAGE_PART_OFFSET)" -D s ::/home/$(CASE) || true
	mcopy -i "$(NEXT_IMAGE)@@$(SD_IMAGE_PART_OFFSET)" -D o $(OUT) ::/home/$(CASE)/

mame: sync
	$(MAME) $(MAME_FLAGS)

clean:
	rm -f cases/*/*.o cases/*/*.lis cases/*/*.map cases/*/*.sym
	rm -rf $(OUTDIR)

.PHONY: all list clean jnext shot mame autoexec sync
