# Minimal ZX Spectrum Next copper test case (z88dk / zcc)
#
#   make        build build/copper-bug.nex
#   make clean  remove build artefacts
#

CC     := zcc
TARGET := +zxn -subtype=nex
CLIB   := sdcc_iy
CRT    := 31

TXT2BAS := txt2bas # Remy Sharp's txt2bas tool (npm install -g txt2bas)
MAME := mame
NEXT_IMAGE := $(HOME)/bin/next-images/cspect-next-2gb.img
SD_IMAGE_PART_OFFSET := 32256
MAME_FLAGS := -snapsize 1440x1080 -ui_active -console -nounevenstretch -video bgfx -bgfx_screen_chains unfiltered -window -skip_gameinfo tbblue -hard1 $(NEXT_IMAGE)

CFLAGS  := $(TARGET) -vn -c -compiler=sdcc -clib=$(CLIB) \
           -SO3 --max-allocs-per-node200000 $(EXTRA_FLAGS)
ASFLAGS := $(TARGET) -vn -c -clib=$(CLIB) $(EXTRA_FLAGS)
LDFLAGS := $(TARGET) -vn -clib=$(CLIB) -startup=$(CRT) -m --list

NAME   := copper-bug
OUTDIR := build
OUT    := $(OUTDIR)/$(NAME).nex
OBJS   := src/main.o src/tilemap.o

all: $(OUT)

# rebuild whenever the flags in this file change
$(OBJS): Makefile

# the tile definitions are incbin'd by src/tilemap.asm
src/tilemap.o: src/game.fnt

$(OUT): $(OBJS) | $(OUTDIR)
	$(CC) $(LDFLAGS) -o $(OUTDIR)/$(NAME).bin $(OBJS) -create-app

$(OUTDIR):
	mkdir -p $(OUTDIR)

%.o: %.c
	$(CC) $(CFLAGS) $< -o $@

%.o: %.asm
	$(CC) $(ASFLAGS) $< -o $@

autoexec:
	@printf '%s\n' \
		'10 REM $(PROJECT_NAME)' \
		'15 REM Autoexec generated by Makefile' \
		'20 CD "c:/home/$(NAME)"' \
		'40 .nexload $(NAME).nex' \
		| $(TXT2BAS) -A 10 | mcopy -i "$(NEXT_IMAGE)@@$(SD_IMAGE_PART_OFFSET)" -D o - ::/nextzxos/autoexec.bas


sync: autoexec $(OUT)
	mmd -i "$(NEXT_IMAGE)@@$(SD_IMAGE_PART_OFFSET)" -D s ::/home/$(NAME) || true
	mcopy -i "$(NEXT_IMAGE)@@$(SD_IMAGE_PART_OFFSET)" -D o build/$(NAME).nex ::/home/$(NAME)/

mame: sync
	$(MAME) $(MAME_PLUGINS) $(MAME_FLAGS) 

jnext: $(OUT)
	jnext --load $(OUT)

clean:
	rm -f src/*.o src/*.lis src/*.map $(OUTDIR)/*

.PHONY: all clean mame autoexec sync
